<?php
$this->load->view('comman/header.php');
$this->load->view('comman/all_modals.php');
//$this->load->view('comman/sidebar.php');
//$this->load->view('comman/top.php');
$this->load->view($view);
$this->load->view('comman/footer');
//$this->load->view('comman/js');
?>